nombre = input("Ingrese su Nombre: ")
apellido = input("Ingrese su Apellido: ")
rut = input("Ingrese su Rut: ")
email = input("Ingrese su email de Duoc: ")
sede = input("Ingrese su Sede: ")
print()
print()
print("Sus datos son: ")
print(nombre)
print(apellido)
print(rut)
print(email)
print(sede)
